FROM ://microsoft.com AS base
WORKDIR /app
EXPOSE 8080

FROM ://microsoft.com AS build
WORKDIR /src

COPY ["FleetManagerApi.csproj", "./"]
RUN dotnet restore "FleetManagerApi.csproj"

COPY . .
RUN dotnet build "FleetManagerApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FleetManagerApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FleetManagerApi.dll"]